package projectv01.GUI;


import Logic.PolytechnicStudent;
import java.awt.CardLayout;

// all the bellow libraries only to do rounded panel :)
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTextField;
import projectv01.GUI.PopUp.GlassPanePopup;
import project01.GUI.datechooser.EventDateChooser;
import project01.GUI.datechooser.SelectedAction;
import project01.GUI.datechooser.SelectedDate;
import java.awt.Color;
import java.util.Date;

public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    CardLayout cardLayout;

    public MainPage() {
        initComponents();
        GlassPanePopup.install(this);
        cardLayout = (CardLayout) (pnlCards.getLayout());

        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmpGenderButtonGroup = new javax.swing.ButtonGroup();
        employeeTypeButtonGroup = new javax.swing.ButtonGroup();
        memberTypeGroupButton = new javax.swing.ButtonGroup();
        MembersGenderButtonGroup = new javax.swing.ButtonGroup();
        dateChooser = new project01.GUI.datechooser.DateChooser();
        mainPage = new javax.swing.JSplitPane();
        nvigPnl = new javax.swing.JPanel();
        emoployeeSectionLabel = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JButton();
        manageEmployeesButton = new javax.swing.JButton();
        listTrainersButton = new javax.swing.JButton();
        memberSectionLabel = new javax.swing.JLabel();
        addMemberButton = new javax.swing.JButton();
        manageMembersButton = new javax.swing.JButton();
        assignTrainerButton = new javax.swing.JButton();
        dashboardButton = new javax.swing.JButton();
        listTrainersButton1 = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        dashboardPnl = new javax.swing.JPanel();
        button1 = new projectv01.GUI.Button();
        addEmployeePnl = new javax.swing.JPanel();
        jPanel1 = new RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPhoneNumberEmpInput = new projectv01.GUI.TextField();
        txtSurnameEmpInput = new projectv01.GUI.TextField();
        txtFirstNameEmpInput = new projectv01.GUI.TextField();
        txtSalaryEmpInput = new projectv01.GUI.TextField();
        txtAddressEmpInput = new projectv01.GUI.TextField();
        jLabel19 = new javax.swing.JLabel();
        RegularEmpbtn = new projectv01.GUI.RadioButtonCustom();
        EmpFemalebtn = new projectv01.GUI.RadioButtonCustom();
        EmpMalebtn = new projectv01.GUI.RadioButtonCustom();
        TrainerEmpbtn = new projectv01.GUI.RadioButtonCustom();
        AddEmpbtn = new projectv01.GUI.Button();
        CancelEmpbtn = new projectv01.GUI.Button();
        addMemberPnl = new javax.swing.JPanel();
        jPanel3 = new RoundPanel();
        jLabel15 = new javax.swing.JLabel();
        Cancelbtn = new projectv01.GUI.Button();
        Addbtn = new projectv01.GUI.Button();
        leftpanel = new javax.swing.JPanel();
        txtMemberPhoneNumberInput = new projectv01.GUI.TextField();
        jLabel18 = new javax.swing.JLabel();
        txtMemberSurnameInput = new projectv01.GUI.TextField();
        jLabel25 = new javax.swing.JLabel();
        txtMemberFirstNameInput = new projectv01.GUI.TextField();
        jLabel17 = new javax.swing.JLabel();
        MiddlePanel = new javax.swing.JPanel();
        Studentbtn = new projectv01.GUI.RadioButtonCustom();
        Staffbtn = new projectv01.GUI.RadioButtonCustom();
        jLabel31 = new javax.swing.JLabel();
        lblMajorOrPosition = new javax.swing.JLabel();
        txtMemberMajorOrPositionInput = new projectv01.GUI.TextField();
        lblSportTeamOrDepartment = new javax.swing.JLabel();
        txtMemberSportTeamOrDepartmentInput = new projectv01.GUI.TextField();
        RightPanel = new javax.swing.JPanel();
        txtMemberAddressInput = new projectv01.GUI.TextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        malebtn = new projectv01.GUI.RadioButtonCustom();
        femalebtn = new projectv01.GUI.RadioButtonCustom();
        txtMemberDateInput = new projectv01.GUI.TextField();
        PickDatebtn = new projectv01.GUI.Button();
        jLabel20 = new javax.swing.JLabel();
        manageEmployeesPnl = new javax.swing.JPanel();
        jPanel4 = new RoundPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        manageMembersPnl = new javax.swing.JPanel();
        jPanel2 = new RoundPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        dateChooser.setTextRefernce(txtMemberDateInput);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gym System\n");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1036, 586));

        mainPage.setDividerSize(1);

        nvigPnl.setBackground(new java.awt.Color(0, 81, 99));
        nvigPnl.setPreferredSize(new java.awt.Dimension(187, 540));

        emoployeeSectionLabel.setForeground(new java.awt.Color(255, 255, 255));
        emoployeeSectionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/user-alt.png"))); // NOI18N
        emoployeeSectionLabel.setText("Employee Section");
        emoployeeSectionLabel.setIconTextGap(10);

        addEmployeeButton.setBackground(new java.awt.Color(2, 73, 89));
        addEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.setBorderPainted(false);
        addEmployeeButton.setFocusable(false);
        addEmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addEmployeeButton.setIconTextGap(5);
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        manageEmployeesButton.setBackground(new java.awt.Color(2, 73, 89));
        manageEmployeesButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeesButton.setText("Magage Employees");
        manageEmployeesButton.setBorderPainted(false);
        manageEmployeesButton.setFocusable(false);
        manageEmployeesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        manageEmployeesButton.setIconTextGap(5);
        manageEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesButtonActionPerformed(evt);
            }
        });

        listTrainersButton.setBackground(new java.awt.Color(2, 73, 89));
        listTrainersButton.setForeground(new java.awt.Color(255, 255, 255));
        listTrainersButton.setText("List Personal Trainers");
        listTrainersButton.setBorderPainted(false);
        listTrainersButton.setFocusable(false);
        listTrainersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        listTrainersButton.setIconTextGap(5);
        listTrainersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTrainersButtonActionPerformed(evt);
            }
        });

        memberSectionLabel.setForeground(new java.awt.Color(255, 255, 255));
        memberSectionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/user-alt.png"))); // NOI18N
        memberSectionLabel.setText("Members section");
        memberSectionLabel.setIconTextGap(10);

        addMemberButton.setBackground(new java.awt.Color(2, 73, 89));
        addMemberButton.setForeground(new java.awt.Color(255, 255, 255));
        addMemberButton.setText("Add Member");
        addMemberButton.setBorderPainted(false);
        addMemberButton.setFocusable(false);
        addMemberButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addMemberButton.setIconTextGap(5);
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });

        manageMembersButton.setBackground(new java.awt.Color(2, 73, 89));
        manageMembersButton.setForeground(new java.awt.Color(255, 255, 255));
        manageMembersButton.setText("Magage Members");
        manageMembersButton.setBorderPainted(false);
        manageMembersButton.setFocusable(false);
        manageMembersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        manageMembersButton.setIconTextGap(5);
        manageMembersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMembersButtonActionPerformed(evt);
            }
        });

        assignTrainerButton.setBackground(new java.awt.Color(2, 73, 89));
        assignTrainerButton.setForeground(new java.awt.Color(255, 255, 255));
        assignTrainerButton.setText("Assign a trainer");
        assignTrainerButton.setBorderPainted(false);
        assignTrainerButton.setFocusable(false);
        assignTrainerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        assignTrainerButton.setIconTextGap(5);
        assignTrainerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTrainerButtonActionPerformed(evt);
            }
        });

        dashboardButton.setBackground(new java.awt.Color(2, 73, 89));
        dashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/dashboardIcon.png"))); // NOI18N
        dashboardButton.setText("DashBoard");
        dashboardButton.setActionCommand("   ");
        dashboardButton.setBorderPainted(false);
        dashboardButton.setFocusable(false);
        dashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        dashboardButton.setIconTextGap(15);
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });

        listTrainersButton1.setBackground(new java.awt.Color(2, 73, 89));
        listTrainersButton1.setForeground(new java.awt.Color(255, 255, 255));
        listTrainersButton1.setText("Asign Member to Trainer");
        listTrainersButton1.setBorderPainted(false);
        listTrainersButton1.setFocusable(false);
        listTrainersButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        listTrainersButton1.setIconTextGap(5);
        listTrainersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTrainersButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nvigPnlLayout = new javax.swing.GroupLayout(nvigPnl);
        nvigPnl.setLayout(nvigPnlLayout);
        nvigPnlLayout.setHorizontalGroup(
            nvigPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nvigPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emoployeeSectionLabel)
                .addGap(39, 39, 39))
            .addComponent(listTrainersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageEmployeesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addEmployeeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listTrainersButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addMemberButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageMembersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(assignTrainerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nvigPnlLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(memberSectionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nvigPnlLayout.setVerticalGroup(
            nvigPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nvigPnlLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emoployeeSectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmployeeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageEmployeesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listTrainersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listTrainersButton1)
                .addGap(25, 25, 25)
                .addComponent(memberSectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addMemberButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageMembersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignTrainerButton)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        mainPage.setLeftComponent(nvigPnl);

        pnlCards.setBackground(new java.awt.Color(2, 73, 89));
        pnlCards.setLayout(new java.awt.CardLayout());

        dashboardPnl.setBackground(new java.awt.Color(0, 143, 140));

        button1.setText("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardPnlLayout = new javax.swing.GroupLayout(dashboardPnl);
        dashboardPnl.setLayout(dashboardPnlLayout);
        dashboardPnlLayout.setHorizontalGroup(
            dashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPnlLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        dashboardPnlLayout.setVerticalGroup(
            dashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPnlLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );

        pnlCards.add(dashboardPnl, "dashboardPnl");

        addEmployeePnl.setBackground(new java.awt.Color(0, 143, 140));
        addEmployeePnl.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(199, 255, 237));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 405));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add Employee form");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("First name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Phone number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Salary");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Surname");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Gender");

        txtPhoneNumberEmpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberEmpInputActionPerformed(evt);
            }
        });

        txtSurnameEmpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurnameEmpInputActionPerformed(evt);
            }
        });

        txtFirstNameEmpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameEmpInputActionPerformed(evt);
            }
        });

        txtSalaryEmpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryEmpInputActionPerformed(evt);
            }
        });

        txtAddressEmpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressEmpInputActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Employee type");

        employeeTypeButtonGroup.add(RegularEmpbtn);
        RegularEmpbtn.setText("Regular");
        RegularEmpbtn.setFocusable(false);

        EmpGenderButtonGroup.add(EmpFemalebtn);
        EmpFemalebtn.setText("Female");
        EmpFemalebtn.setFocusable(false);
        EmpFemalebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpFemalebtnActionPerformed(evt);
            }
        });

        EmpGenderButtonGroup.add(EmpMalebtn);
        EmpMalebtn.setText("Male");
        EmpMalebtn.setFocusable(false);
        EmpMalebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpMalebtnActionPerformed(evt);
            }
        });

        employeeTypeButtonGroup.add(TrainerEmpbtn);
        TrainerEmpbtn.setText("Trainer");
        TrainerEmpbtn.setFocusable(false);

        AddEmpbtn.setBackground(new java.awt.Color(0, 143, 140));
        AddEmpbtn.setText("Add");
        AddEmpbtn.setFocusable(false);
        AddEmpbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AddEmpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpbtnActionPerformed(evt);
            }
        });

        CancelEmpbtn.setBackground(new java.awt.Color(204, 0, 51));
        CancelEmpbtn.setText("Cancel");
        CancelEmpbtn.setFocusable(false);
        CancelEmpbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CancelEmpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelEmpbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(AddEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(CancelEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(txtSurnameEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txtSalaryEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtFirstNameEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtAddressEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EmpMalebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EmpFemalebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumberEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RegularEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(TrainerEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RegularEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpFemalebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpMalebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TrainerEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFirstNameEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurnameEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumberEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalaryEmpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelEmpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout addEmployeePnlLayout = new javax.swing.GroupLayout(addEmployeePnl);
        addEmployeePnl.setLayout(addEmployeePnlLayout);
        addEmployeePnlLayout.setHorizontalGroup(
            addEmployeePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePnlLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        addEmployeePnlLayout.setVerticalGroup(
            addEmployeePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePnlLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pnlCards.add(addEmployeePnl, "addEmployeePnl");

        addMemberPnl.setBackground(new java.awt.Color(0, 143, 140));
        addMemberPnl.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(199, 255, 237));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(710, 405));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Add Member form");

        Cancelbtn.setBackground(new java.awt.Color(204, 0, 51));
        Cancelbtn.setText("Cancel");
        Cancelbtn.setFocusable(false);
        Cancelbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        Addbtn.setBackground(new java.awt.Color(0, 143, 140));
        Addbtn.setText("Add");
        Addbtn.setFocusable(false);
        Addbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        leftpanel.setBackground(new java.awt.Color(199, 255, 237));

        txtMemberPhoneNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberPhoneNumberInputActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Phone number");

        txtMemberSurnameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberSurnameInputActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Surname");

        txtMemberFirstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberFirstNameInputActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("First name");

        javax.swing.GroupLayout leftpanelLayout = new javax.swing.GroupLayout(leftpanel);
        leftpanel.setLayout(leftpanelLayout);
        leftpanelLayout.setHorizontalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtMemberFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel18)
                            .addComponent(txtMemberPhoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtMemberSurnameInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        leftpanelLayout.setVerticalGroup(
            leftpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftpanelLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemberFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemberSurnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemberPhoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        MiddlePanel.setBackground(new java.awt.Color(199, 255, 237));

        memberTypeGroupButton.add(Studentbtn);
        Studentbtn.setSelected(true);
        Studentbtn.setText("Student");
        Studentbtn.setFocusable(false);
        Studentbtn.setPreferredSize(new java.awt.Dimension(64, 41));
        Studentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentbtnActionPerformed(evt);
            }
        });

        memberTypeGroupButton.add(Staffbtn);
        Staffbtn.setText("Staff");
        Staffbtn.setFocusPainted(false);
        Staffbtn.setPreferredSize(new java.awt.Dimension(47, 41));
        Staffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffbtnActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Member type");

        lblMajorOrPosition.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMajorOrPosition.setForeground(new java.awt.Color(0, 0, 0));
        lblMajorOrPosition.setText("Major");

        txtMemberMajorOrPositionInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberMajorOrPositionInputActionPerformed(evt);
            }
        });

        lblSportTeamOrDepartment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSportTeamOrDepartment.setForeground(new java.awt.Color(0, 0, 0));
        lblSportTeamOrDepartment.setText("SportTeam ");

        txtMemberSportTeamOrDepartmentInput.setText(" ");
        txtMemberSportTeamOrDepartmentInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberSportTeamOrDepartmentInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MiddlePanelLayout = new javax.swing.GroupLayout(MiddlePanel);
        MiddlePanel.setLayout(MiddlePanelLayout);
        MiddlePanelLayout.setHorizontalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(MiddlePanelLayout.createSequentialGroup()
                        .addComponent(Studentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Staffbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMajorOrPosition)
                    .addComponent(txtMemberMajorOrPositionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSportTeamOrDepartment)
                    .addComponent(txtMemberSportTeamOrDepartmentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MiddlePanelLayout.setVerticalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Studentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staffbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 29, Short.MAX_VALUE)
                .addComponent(lblMajorOrPosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemberMajorOrPositionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                .addComponent(lblSportTeamOrDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemberSportTeamOrDepartmentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        RightPanel.setBackground(new java.awt.Color(199, 255, 237));

        txtMemberAddressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberAddressInputActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Address");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Gender");

        MembersGenderButtonGroup.add(malebtn);
        malebtn.setText("Male");
        malebtn.setFocusable(false);
        malebtn.setPreferredSize(new java.awt.Dimension(49, 41));
        malebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malebtnActionPerformed(evt);
            }
        });

        MembersGenderButtonGroup.add(femalebtn);
        femalebtn.setText("Female");
        femalebtn.setFocusPainted(false);
        femalebtn.setFocusable(false);
        femalebtn.setPreferredSize(new java.awt.Dimension(61, 41));
        femalebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalebtnActionPerformed(evt);
            }
        });

        txtMemberDateInput.setText(" ");
        txtMemberDateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberDateInputActionPerformed(evt);
            }
        });

        PickDatebtn.setText("Pick");
        PickDatebtn.setFocusPainted(false);
        PickDatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickDatebtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Date of Birth");

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RightPanelLayout.createSequentialGroup()
                                .addComponent(txtMemberDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PickDatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel20)
                            .addComponent(txtMemberAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addGroup(RightPanelLayout.createSequentialGroup()
                                .addComponent(malebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(femalebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femalebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMemberAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMemberDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PickDatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(leftpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(MiddlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MiddlePanel, RightPanel, leftpanel});

        javax.swing.GroupLayout addMemberPnlLayout = new javax.swing.GroupLayout(addMemberPnl);
        addMemberPnl.setLayout(addMemberPnlLayout);
        addMemberPnlLayout.setHorizontalGroup(
            addMemberPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMemberPnlLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        addMemberPnlLayout.setVerticalGroup(
            addMemberPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMemberPnlLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlCards.add(addMemberPnl, "addMemberPnl");

        manageEmployeesPnl.setBackground(new java.awt.Color(0, 143, 140));
        manageEmployeesPnl.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(199, 255, 237));
        jPanel4.setPreferredSize(new java.awt.Dimension(710, 405));

        jTextField4.setBackground(new java.awt.Color(11, 196, 217));
        jTextField4.setToolTipText("Search By ID");
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Employee Name");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Employee ID");

        jButton9.setBackground(new java.awt.Color(11, 196, 217));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/pen.png"))); // NOI18N
        jButton9.setText("Edit");
        jButton9.setToolTipText("");
        jButton9.setBorder(null);
        jButton9.setFocusPainted(false);
        jButton9.setIconTextGap(10);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/searchIcon.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Employee Type");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("202101379");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Ali Jasim");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Regular");

        jButton10.setBackground(new java.awt.Color(11, 196, 217));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/trashIconImage.png"))); // NOI18N
        jButton10.setText("Delete");
        jButton10.setToolTipText("");
        jButton10.setBorder(null);
        jButton10.setIconTextGap(10);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel22, jLabel28});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel14, jLabel29});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel27, jLabel30});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel14)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(jButton10))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29)
                        .addComponent(jLabel30)))
                .addContainerGap(345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout manageEmployeesPnlLayout = new javax.swing.GroupLayout(manageEmployeesPnl);
        manageEmployeesPnl.setLayout(manageEmployeesPnlLayout);
        manageEmployeesPnlLayout.setHorizontalGroup(
            manageEmployeesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEmployeesPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageEmployeesPnlLayout.setVerticalGroup(
            manageEmployeesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEmployeesPnlLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlCards.add(manageEmployeesPnl, "manageEmployeesPnl");

        manageMembersPnl.setBackground(new java.awt.Color(0, 143, 140));
        manageMembersPnl.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(199, 255, 237));
        jPanel2.setPreferredSize(new java.awt.Dimension(710, 405));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setToolTipText("Search By ID");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Member Name");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Member ID");

        jButton4.setBackground(new java.awt.Color(11, 196, 217));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/pen.png"))); // NOI18N
        jButton4.setText("Edit");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.setFocusPainted(false);
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/searchIcon.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Personal Trainer");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("202101379");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ali Jasim");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Regular");

        jButton8.setBackground(new java.awt.Color(11, 196, 217));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectv01/GUI/images/trashIconImage.png"))); // NOI18N
        jButton8.setText("Delete");
        jButton8.setToolTipText("");
        jButton8.setBorder(null);
        jButton8.setIconTextGap(10);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel13, jLabel9});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel12});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel16});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)))
                .addContainerGap(345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout manageMembersPnlLayout = new javax.swing.GroupLayout(manageMembersPnl);
        manageMembersPnl.setLayout(manageMembersPnlLayout);
        manageMembersPnlLayout.setHorizontalGroup(
            manageMembersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMembersPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageMembersPnlLayout.setVerticalGroup(
            manageMembersPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMembersPnlLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pnlCards.add(manageMembersPnl, "manageMembersPnl");

        mainPage.setRightComponent(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPage, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPage)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        cardLayout.show(pnlCards, "dashboardPnl");
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        cardLayout.show(pnlCards, "addEmployeePnl");
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void manageEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "manageEmployeesPnl");
    }//GEN-LAST:event_manageEmployeesButtonActionPerformed

    private void listTrainersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTrainersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listTrainersButtonActionPerformed

    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "addMemberPnl");
    }//GEN-LAST:event_addMemberButtonActionPerformed

    private void manageMembersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMembersButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "manageMembersPnl");
    }//GEN-LAST:event_manageMembersButtonActionPerformed

    private void assignTrainerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTrainerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignTrainerButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void listTrainersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTrainersButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listTrainersButton1ActionPerformed

    private void txtPhoneNumberEmpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberEmpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberEmpInputActionPerformed

    private void txtSurnameEmpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameEmpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameEmpInputActionPerformed

    private void txtFirstNameEmpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameEmpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameEmpInputActionPerformed

    private void txtSalaryEmpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryEmpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryEmpInputActionPerformed

    private void txtAddressEmpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressEmpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressEmpInputActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        Message obj = new Message();
        obj.eventOK(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                System.out.println("Click OK");
                GlassPanePopup.closePopupLast();
            }
        });
        GlassPanePopup.showPopup(obj);


    }//GEN-LAST:event_button1ActionPerformed

    private void txtMemberDateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberDateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberDateInputActionPerformed

    private void femalebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femalebtnActionPerformed

    private void malebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_malebtnActionPerformed

    private void txtMemberAddressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberAddressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberAddressInputActionPerformed

    private void txtMemberSportTeamOrDepartmentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberSportTeamOrDepartmentInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberSportTeamOrDepartmentInputActionPerformed

    private void txtMemberMajorOrPositionInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberMajorOrPositionInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberMajorOrPositionInputActionPerformed

    private void StaffbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffbtnActionPerformed
        // TODO add your handling code here:
        lblSportTeamOrDepartment.setText("Department");
        lblMajorOrPosition.setText("Position");
        txtMemberMajorOrPositionInput.setText("");
        txtMemberSportTeamOrDepartmentInput.setText("");
    }//GEN-LAST:event_StaffbtnActionPerformed

    private void StudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentbtnActionPerformed
        // TODO add your handling code here:
        lblSportTeamOrDepartment.setText("Sport Team");
        lblMajorOrPosition.setText("Major");
        txtMemberMajorOrPositionInput.setText("");
        txtMemberSportTeamOrDepartmentInput.setText("");
    }//GEN-LAST:event_StudentbtnActionPerformed

    private void txtMemberFirstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberFirstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberFirstNameInputActionPerformed

    private void txtMemberSurnameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberSurnameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberSurnameInputActionPerformed

    private void txtMemberPhoneNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberPhoneNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberPhoneNumberInputActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed

         ArrayList<String> txtStrAllList = new ArrayList<>();
        txtStrAllList.add("First Name");
        txtStrAllList.add("Surname");

        ArrayList<String> txtAllList = new ArrayList<>();
        txtAllList.add("First Name");
        txtAllList.add("Surname");
        txtAllList.add("Phone number");
        txtAllList.add("Address");
        txtAllList.add("Date of Birth");
        
        
        if (Studentbtn.isSelected()) {
            txtStrAllList.add("Major");
            txtAllList.add("Major");
        } else {
            txtStrAllList.add("Position");
            txtStrAllList.add("Department");
            txtAllList.add("Position");
            txtAllList.add("Department");
        }

        if (Studentbtn.isSelected()) {
            for (int i = 0; i < addMemberStuAllTxt().size(); i++) {
                if (!isfilled(addMemberStuAllTxt().get(i), txtAllList.get(i))) {
                    return;
                }
            }
            for (int i = 0; i < addMemberStuStrTxt().size(); i++) {
                if (!containsOnlyLetters(addMemberStuStrTxt().get(i), txtStrAllList.get(i))) {
                    return;
                }
            }
        } else {
            for (int i = 0; i < addMemberAllTxt().size(); i++) {
                if (!isfilled(addMemberAllTxt().get(i), txtAllList.get(i))) {
                    return;
                }
            }
            for (int i = 0; i < addMemberStrTxt().size(); i++) {
                if (!containsOnlyLetters(addMemberStrTxt().get(i), txtStrAllList.get(i))) {
                    return;
                }
            }
        }

        if (!numbersOnly(txtMemberPhoneNumberInput)) {
            return;
        }
        
        if (!malebtn.isSelected() & !femalebtn.isSelected()) {
            PopupMessage("please choose a gender");
            return;
        }
        String gender = femalebtn.isSelected() ?  "Female":"Male" ; 
        if (Studentbtn.isSelected()){
                PolytechnicStudent jaffer = new PolytechnicStudent(1, txtMemberFirstNameInput.getText(), txtMemberSurnameInput.getText(), txtMemberAddressInput.getText(), txtMemberPhoneNumberInput.getText(), gender, txtMemberDateInput.getText(),txtMemberMajorOrPositionInput.getText(),txtMemberSportTeamOrDepartmentInput.getText());
        }else{
            
        }
  
    }//GEN-LAST:event_AddbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        clearTextFields(addMemberAllTxt());
        MembersGenderButtonGroup.clearSelection();
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void PickDatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickDatebtnActionPerformed
        dateChooser.showPopup();
    }//GEN-LAST:event_PickDatebtnActionPerformed

    private void AddEmpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpbtnActionPerformed
        // TODO add your handling code here:
        final String[] txt = {"First Name", "Surname"};
        final String[] all = {"First Name", "Surname", "Salary", "Address", "Phone Number"};

        for (int i = 0; i < addEmployeeAllTxt().size(); i++) {
            if (!isfilled(addEmployeeAllTxt().get(i), all[i])) {
                return;
            }
        }

        for (int i = 0; i < txt.length; i++) {
            if (!containsOnlyLetters(addEmployeeAllTxt().get(i), txt[i])) {
                return;
            }
        }

        if (!numbersOnly(txtSalaryEmpInput)) {
            return;
        }

        if (!numbersOnly(txtPhoneNumberEmpInput)) {
            return;
        }

        if (!EmpMalebtn.isSelected() & !EmpFemalebtn.isSelected()) {
            PopupMessage("please choose a gender");
            return;
        }

        if (!RegularEmpbtn.isSelected() & !TrainerEmpbtn.isSelected()) {
            PopupMessage("please choose a Member type");
            return;
        }
    }//GEN-LAST:event_AddEmpbtnActionPerformed

    private void CancelEmpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelEmpbtnActionPerformed
        // TODO add your handling code here:
        clearTextFields(addEmployeeAllTxt());
        EmpGenderButtonGroup.clearSelection();
        employeeTypeButtonGroup.clearSelection();
    }//GEN-LAST:event_CancelEmpbtnActionPerformed

    private void EmpMalebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpMalebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpMalebtnActionPerformed

    private void EmpFemalebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpFemalebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpFemalebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projectv01.GUI.Button AddEmpbtn;
    private projectv01.GUI.Button Addbtn;
    private projectv01.GUI.Button CancelEmpbtn;
    private projectv01.GUI.Button Cancelbtn;
    private projectv01.GUI.RadioButtonCustom EmpFemalebtn;
    private javax.swing.ButtonGroup EmpGenderButtonGroup;
    private projectv01.GUI.RadioButtonCustom EmpMalebtn;
    private javax.swing.ButtonGroup MembersGenderButtonGroup;
    private javax.swing.JPanel MiddlePanel;
    private projectv01.GUI.Button PickDatebtn;
    private projectv01.GUI.RadioButtonCustom RegularEmpbtn;
    private javax.swing.JPanel RightPanel;
    private projectv01.GUI.RadioButtonCustom Staffbtn;
    private projectv01.GUI.RadioButtonCustom Studentbtn;
    private projectv01.GUI.RadioButtonCustom TrainerEmpbtn;
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JPanel addEmployeePnl;
    private javax.swing.JButton addMemberButton;
    private javax.swing.JPanel addMemberPnl;
    private javax.swing.JButton assignTrainerButton;
    private projectv01.GUI.Button button1;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JPanel dashboardPnl;
    private project01.GUI.datechooser.DateChooser dateChooser;
    private javax.swing.JLabel emoployeeSectionLabel;
    private javax.swing.ButtonGroup employeeTypeButtonGroup;
    private projectv01.GUI.RadioButtonCustom femalebtn;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblMajorOrPosition;
    private javax.swing.JLabel lblSportTeamOrDepartment;
    private javax.swing.JPanel leftpanel;
    private javax.swing.JButton listTrainersButton;
    private javax.swing.JButton listTrainersButton1;
    private javax.swing.JSplitPane mainPage;
    private projectv01.GUI.RadioButtonCustom malebtn;
    private javax.swing.JButton manageEmployeesButton;
    private javax.swing.JPanel manageEmployeesPnl;
    private javax.swing.JButton manageMembersButton;
    private javax.swing.JPanel manageMembersPnl;
    private javax.swing.JLabel memberSectionLabel;
    private javax.swing.ButtonGroup memberTypeGroupButton;
    private javax.swing.JPanel nvigPnl;
    private javax.swing.JPanel pnlCards;
    private projectv01.GUI.TextField txtAddressEmpInput;
    private projectv01.GUI.TextField txtFirstNameEmpInput;
    private projectv01.GUI.TextField txtMemberAddressInput;
    private projectv01.GUI.TextField txtMemberDateInput;
    private projectv01.GUI.TextField txtMemberFirstNameInput;
    private projectv01.GUI.TextField txtMemberMajorOrPositionInput;
    private projectv01.GUI.TextField txtMemberPhoneNumberInput;
    private projectv01.GUI.TextField txtMemberSportTeamOrDepartmentInput;
    private projectv01.GUI.TextField txtMemberSurnameInput;
    private projectv01.GUI.TextField txtPhoneNumberEmpInput;
    private projectv01.GUI.TextField txtSalaryEmpInput;
    private projectv01.GUI.TextField txtSurnameEmpInput;
    // End of variables declaration//GEN-END:variables

    public boolean isfilled(TextField textField, String error) {
        final Color DefaultC = new Color(170, 170, 170);
        final Color ErrorC = new Color(250, 0, 0);
        textField.setShadowColor(DefaultC);
        String str = textField.getText();

        if (str == null || str.isEmpty() || str.equals(" ")) {
            PopupMessage("Please fill the " + error);
            textField.requestFocus();
            textField.setShadowColor(ErrorC);
            return false;
        }
        return true;
    }

    public boolean containsOnlyLetters(TextField textField, String error) {
        final Color DefaultC = new Color(170, 170, 170);
        final Color ErrorC = new Color(250, 0, 0);
        textField.setShadowColor(DefaultC);
        String str = textField.getText();
        boolean found = false;

        for (char c : str.toCharArray()) {
            if (!Character.isLetter(c) && found == false) {
                PopupMessage("Please follow the right cardinalities for " + error);
                found = true;
                textField.requestFocus();
                textField.setShadowColor(ErrorC);
                return false;
            }
        }
        return true;
    }

    public static void PopupMessage(String error) {
        Message obj = new Message();
        obj.SetLabel(error);
        obj.eventOK(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                GlassPanePopup.closePopupLast();
            }
        });
        GlassPanePopup.showPopup(obj);
    }

    public boolean numbersOnly(TextField textField) {
        String input = textField.getText();
        final String allowedChars = "0123456789";
        final Color DefaultC = new Color(170, 170, 170);
        final Color ErrorC = new Color(250, 0, 0);
        textField.setShadowColor(DefaultC);

        for (int i = 0; i < input.length(); i++) {
            char c = input.charAt(i);
            if (allowedChars.indexOf(c) == -1) {
                PopupMessage("Please follow the right cardinalities for the pohne numbers or salary ");
                textField.requestFocus();
                textField.setShadowColor(ErrorC);
                return false;
            }
        }

        return true;
    }

    public void clearTextFields(ArrayList<TextField> textFields) {
        final Color DefaultC = new Color(170, 170, 170);
        for (TextField textField : textFields) {
            textField.setText("");
            textField.setShadowColor(DefaultC);
        }
    }

    public ArrayList<TextField> addMemberAllTxt() {
        ArrayList<TextField> addMemberTxt = new ArrayList<>();
        addMemberTxt.add(txtMemberFirstNameInput);
        addMemberTxt.add(txtMemberSurnameInput);
        addMemberTxt.add(txtMemberPhoneNumberInput);
        addMemberTxt.add(txtMemberAddressInput);
        addMemberTxt.add(txtMemberDateInput);
        addMemberTxt.add(txtMemberMajorOrPositionInput);
        addMemberTxt.add(txtMemberSportTeamOrDepartmentInput);

        return addMemberTxt;
    }

    public ArrayList<TextField> addMemberStrTxt() {
        ArrayList<TextField> addMemberTxt = new ArrayList<>();
        addMemberTxt.add(txtMemberFirstNameInput);
        addMemberTxt.add(txtMemberSurnameInput);
        addMemberTxt.add(txtMemberMajorOrPositionInput);
        addMemberTxt.add(txtMemberSportTeamOrDepartmentInput);

        return addMemberTxt;
    }

    public ArrayList<TextField> addMemberStuAllTxt() {
        ArrayList<TextField> addMemberTxt = new ArrayList<>();
        addMemberTxt.add(txtMemberFirstNameInput);
        addMemberTxt.add(txtMemberSurnameInput);
        addMemberTxt.add(txtMemberPhoneNumberInput);
        addMemberTxt.add(txtMemberAddressInput);
        addMemberTxt.add(txtMemberDateInput);
        addMemberTxt.add(txtMemberMajorOrPositionInput);
        return addMemberTxt;
    }

    public ArrayList<TextField> addMemberStuStrTxt() {
        ArrayList<TextField> addMemberTxt = new ArrayList<>();
        addMemberTxt.add(txtMemberFirstNameInput);
        addMemberTxt.add(txtMemberSurnameInput);
        addMemberTxt.add(txtMemberMajorOrPositionInput);
        return addMemberTxt;
    }

    public ArrayList<TextField> addEmployeeAllTxt() {
        ArrayList<TextField> addEmployeeTxt = new ArrayList<>();
        addEmployeeTxt.add(txtFirstNameEmpInput);
        addEmployeeTxt.add(txtSurnameEmpInput);
        addEmployeeTxt.add(txtSalaryEmpInput);
        addEmployeeTxt.add(txtAddressEmpInput);
        addEmployeeTxt.add(txtPhoneNumberEmpInput);
        return addEmployeeTxt;
    }

}
